### ISSUE TITLE
example of `ingress.pomerium.io/from` annotation?

### ISSUE THREAD

**Issue by karel-3d** [pomerium/pomerium-operator#76]
What is the correct `ingress.pomerium.io/from` annotation? I don't see anything in examples.

**Comment by karel-3d** [comment]
Google search for `ingress.pomerium.io/from` gets exactly 1 result, this repo readme.

**Comment by travisgroth** [comment]
If you are using an `Ingress`, it is implicit and not required.  If you are routing directly to a `Service` it would be required since there's no `hosts` block for us to derive your external DNS from.  

See https://www.pomerium.com/reference/#from for syntax.  These annotations are directly converted into pomerium policy options.
